AllCops:
  NewCops: enable
  Exclude:
    - bin/bundle
    - bin/webpack*
    - config/**/*
    - node_modules/**/*
    - db/schema.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Naming/VariableNumber:
  Exclude:
    - spec/**/*

Style/Documentation:
  Exclude:
    - db/migrate/**/*

Style/FrozenStringLiteralComment:
  Exclude:
    - db/migrate/**/*
