AllCops:
  NewCops: enable
  Exclude:
    - bin/bundle
    - config/**/*
    - node_modules/**/*
    - db/schema.rb

Style/Documentation:
  Exclude:
    - db/migrate/**/*

Style/FrozenStringLiteralComment:
  Exclude:
    - db/migrate/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*