default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: abcd1234
  pool: 5

development:
  <<: *default
  database: minutesmaid_development
  # host: localhost

test:
  database: db/test.sqlite3
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

production:
  database: minutesmaid_prod
  username: minutesmaid
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
  pool: 5
  timeout: 5000